#!/usr/bin/env bash
# Installsfigurations:

sudo apt-get update
sudo apt-get -y install nginx

# Cthe Nginx HTTP service
sudo ufw allow 'Nginx HTTP'

# Creatml page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing errors
sudo nginx -t

# RestarNginx
sudo service nginx start
