#!/usr/bin/env bash
# Configures a ntalling


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# sta
sudo service nginx start

# allow
sudo ufw allow 'Nginx HTTP'

# Gi
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creatin
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Re nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
