#!/usr/bin/env bash
#  A Script a 301-redirection

# Upadatstallations
sudo apt-get update
sudo apt-get install -y nginx

# Creatiage
echo "Hello World!" | sudo tee /var/www/html/index.html

# Pirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restservice
sudo service nginx restart
