#!/usr/bin/env bash
# Cust err r page

# Upn tallatons
sudo apt-get update
sudo apt-get install -y nginx

# Cre age
echo "Hello World!" | sudo tee /var/www/html/index.html

# Pe edirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# eati
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Testiors
sudo nginx -t

# rest anges
sudo service nginx restart
