#!/usr/bin/env bash
# Creates

# Installs
sudo apt-get -y update
apt-get -y install haproxy

# edits
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 176572-web-01 54.165.168.252:80 check
        server 176572-web-02 34.237.91.136:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enables
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testings
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restarts
sudo service haproxy restart
